name: Deploy
on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ap-southeast-2

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Configure AWS Credentials for tenant-adatree-saas-prod
        uses: aws-actions/configure-aws-credentials@v1-node16
        if: github.ref == 'refs/heads/main'
        with:
          role-to-assume: arn:aws:iam::509445696409:role/WorkloadAccountDeployRole
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 1200